### ISSUE TITLE
Fails without including `set` explicitly

### ISSUE THREAD

**Issue by estiens** [matl33t/apa102_rbpi#6]
Without including set explicitly, everything fails because `strip` uses Set.new (so you get `NameError: uninitialized constant Apa102Rbpi::Strip::Set`) -- suggested fix -- `require set` in strip.rb  :)

**Comment by tibbon** [comment]
I think there was a regression and it's no longer in there.

**Comment by matl33t** [comment]
@tibbon thanks, this is now (re)fixed in the latest version.
